### ISSUE TITLE
I want the block to recover from "Unauthorized" 401 error

### ISSUE THREAD

**Issue by hansmosh** [nio-blocks/reddit#5]
I would expect that the block needs to re-authorize when this happens:

> [2016-08-08 15:11:46.957] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wqlul returned status 401: {'error': 401, 'message': 'Unauthorized'}
> [2016-08-08 16:11:53.427] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wqwog returned status 401: {'error': 401, 'message': 'Unauthorized'}
> [2016-08-08 17:11:53.525] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wr81y returned status 401: {'error': 401, 'message': 'Unauthorized'}
> [2016-08-08 18:12:02.026] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wrkhn returned status 401: {'error': 401, 'message': 'Unauthorized'}
> [2016-08-08 19:12:08.931] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wrw7h returned status 401: {'error': 401, 'message': 'Unauthorized'}
> [2016-08-08 20:12:15.807] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4ws7qs returned status 401: {'error': 401, 'message': 'Unauthorized'}
> [2016-08-08 21:12:24.209] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wsiyh returned status 401: {'error': 401, 'message': 'Unauthorized'}
> [2016-08-08 21:29:01.282] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wslyi returned status 503: <Response [503]>
> [2016-08-08 22:26:26.105] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wsvtj returned status 503: <Response [503]>
> [2016-08-08 22:27:46.347] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wsvu9 returned status 520: <Response [520]>
> [2016-08-08 23:08:16.843] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wt2wg returned status 503: <Response [503]>
> [2016-08-09 00:08:22.821] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wtcxu returned status 401: {'error': 401, 'message': 'Unauthorized'}
> [2016-08-09 01:08:25.335] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wtmce returned status 401: {'error': 401, 'message': 'Unauthorized'}
> [2016-08-09 01:18:41.276] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wtnxh returned status 500: {'error': 500, 'message': 'Internal Server Error'}
> [2016-08-09 01:19:46.721] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wtnxh returned status 503: <Response [503]>
> [2016-08-09 01:21:56.727] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wtnxh returned status 503: <Response [503]>
> [2016-08-09 01:26:12.202] NIO [WARNING] [Reddit.RedditFetch] Polling request of https://oauth.reddit.com/r/all/new.json?before=t3_4wtnxh returned status 503: <Response [503]>
> [2016-08-09 01:26:22.579] NIO [ERROR] [Reddit.RedditFetch] Out of retries. Aborting and changing status to Error.

**Comment by hansmosh** [comment]
@mattdodge on slack:

> the fact that there are some 503 and 520 errors in there makes me think it was all just server side, I think the block (especially once it gets the retry mixin) should be fine

**Comment by dorzel** [comment]
@hansmosh @mattdodge Closing this as the block has retry functionality now through the RestPolling block.
